web-app/src/app.py
# @Author      : 'Savvy'
# @Created_date: 2018/12/5 3:54 PM

import os
from flask import Flask, render_template
from src.database import Database
from src.models.locations.views import location_blueprint
from src.models.visions.views import vision_blueprint

tmpl_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'templates')
app = Flask(__name__, template_folder=tmpl_dir)
app.config.from_object('src.config')
app.secret_key = "123"
app.register_blueprint(location_blueprint, url_prefix="/locations")
app.register_blueprint(vision_blueprint, url_prefix="/visions")


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template("home.jinja2")


app.run(host='0.0.0.0', debug=app.config['DEBUG'], port=5050)

web-app/src/models/locations/__init__.py
# @Author      : 'Savvy'
# @Created_date: 2018/12/5 4:40 PM

web-app/src/models/locations/views.py
# @Author      : 'Savvy'
# @Created_date: 2018/12/5 4:44 PM

from flask import Flask, request, Response, Blueprint
from src.models.locations.location import Location
import json
import jsonpickle

location_blueprint = Blueprint('locations', __name__)


@location_blueprint.route('/save_loc', methods=['POST'])
def save_location():
    # convert string of image data to uint8
    coord_data = json.loads(request.data.decode('utf-8'))
    print(coord_data)

    loc = Location(coord_data)
    print(loc.time)
    loc.save_to_db()

    # build a response dict to send back to client
    response = {'message': 'location info received...'}
    # encode response using jsonpickle
    response_pickled = jsonpickle.encode(response)

    return Response(response=response_pickled, status=200, mimetype="application/json")

web-app/src/models/visions/__init__.py
# @Author      : 'Savvy'
# @Created_date: 2018/12/5 4:40 PM

web-app/src/models/visions/views.py
# @Author      : 'Savvy'
# @Created_date: 2018/12/5 4:44 PM

from flask import request, Response, render_template, Blueprint
from src.models.locations.location import Location
from src.models.visions.vision import Vision
import jsonpickle
import datetime
import base64
import pytz

vision_blueprint = Blueprint('visions', __name__)


# route http posts to this method
@vision_blueprint.route('/save_img', methods=['POST'])
def save_image():
    # convert string of image data to uint8

    encoded_string = base64.b64encode(request.data)

    vision = Vision(encoded_string)
    vision.save_to_db()

    # build a response dict to send back to client
    response = {'message': 'image received...'}
    # encode response using jsonpickle
    response_pickled = jsonpickle.encode(response)

    return Response(response=response_pickled, status=200, mimetype="application/json")


@vision_blueprint.route('/view', methods=['GET', 'POST'])
def view():
    if request.method == 'POST':
        raw_time = request.form['timeThreshold']
        time = datetime.datetime.strptime(raw_time, '%m/%d/%y %H:%M:%S')
    else:
        time = datetime.datetime.now(pytz.timezone('US/Eastern'))
    vision = Vision.find_latest_before_time(time)
    location = Location.find_latest_before_time(time)
    tmp = "data:image/jpeg;base64,"+str(vision.image)
    imgStr = tmp[:23] + tmp[25:-1]
    if vision is None or location is None:
        return render_template()

    return render_template("visions/view_image.jinja2", image=imgStr, location=location)

web-app/src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Eyes of Blinds</title>

    {% include 'html_dependencies.jinja2' %}

</head>
<body>

<nav class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" title="Home">Home</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('visions.view') }}" title="Locations">Geo Info</a></li>
                <li><a href="{{ url_for('visions.view') }}" title="Vision">Vision Info</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

web-app/src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron">
        <h1>Online Tracker</h1>
        <p>We offer Vision and Geolocation info about our user.</p>
        <p>Easily check your family members' travel info!</p>
        <form method="post">
            <div class="form-group">
                <label for="timeThreshold"></label>
                <input type="text" class="form-control" id="timeThreshold" name="timeThreshold" placeholder="12/05/18 14:00:00"
                aria-describedby="timeThresholdHelp">
                <span id="timeThresholdHelp" class="help-block">Set the time threshold to search the most recent info before that time</span>
            </div>
            <p><a class="btn btn-primary btn-lg" href="{{ url_for('visions.view') }}" role="button">View</a></p>
        </form>
    </div>
{% endblock %}

web-app/src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

web-app/src/templates/visions/view_image.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Vision & Geolocation Info
            <small>Most recent one before time threshold</small>
        </h1>
    </div>
    <div class="list-group">
        <a class="list-group-item">
            <p><img  src={{ image }}></p>
        </a>
        <a class="list-group-item">
            <h5 class="GeoInfo">(Latitude, Longitude): ({{ location.coord['location']['lat'] }}, {{ location.coord['location']['lng'] }})
                with Accuracy={{ location.coord['accuracy'] }}</h5>
        </a>
    </div>
{% endblock %}